disable_existing_loggers: true
formatters:
  custom_format:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(hostname)s ............. \n\
      \ %(message)s"
  default:
    format: '%(message)s'
  default_file:
    format: "%(asctime)s - %(name)s - %(levelname)s - \n %(message)s"
  simple:
    format: '%(hostname)s-- %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
  critical_file_handler:
    backupCount: 20
    class: logging.handlers.RotatingFileHandler
    encoding: utf8
    filename: C:\Users\MARIOPEREZBENAVIDES\logs\jsnapy\jsnapy.log
    formatter: default_file
    level: CRITICAL
    maxBytes: 10485760
  debug_file_handler:
    backupCount: 20
    class: logging.handlers.RotatingFileHandler
    encoding: utf8
    filename: C:\Users\MARIOPEREZBENAVIDES\logs\jsnapy\jsnapy.log
    formatter: default_file
    level: DEBUG
    maxBytes: 10485760
  error_file_handler:
    backupCount: 20
    class: logging.handlers.RotatingFileHandler
    encoding: utf8
    filename: C:\Users\MARIOPEREZBENAVIDES\logs\jsnapy\jsnapy.log
    formatter: default_file
    level: ERROR
    maxBytes: 10485760
  info_file_handler:
    backupCount: 20
    class: logging.handlers.RotatingFileHandler
    encoding: utf8
    filename: C:\Users\MARIOPEREZBENAVIDES\logs\jsnapy\jsnapy.log
    formatter: default_file
    level: INFO
    maxBytes: 10485760
root:
  handlers:
  - console
  - debug_file_handler
  level: DEBUG
version: 1
